ERROR
Traceback (most recent call last):
  File "process_task.py", line 35, in <module>
    tsa = TSA(task.mp1, task.mp2, depth)
  File "../tsa3.py", line 78, in __init__
    assert len(add) == 1
AssertionError

